N=$a$*w
D=$+d
O=+|-|*|/
E=D|N|E O E
R==|<=|<|>=|>
C=not C|C and C|C or C

L=let N:=E
I=if C then S else S
R=repeat G until C
W=while E do S
A=E,A|E|
F=N(A)
S=L|I|R|W|B|F

G=S;|;
B=begin $*G end
P=program N; B.$e

?A
1
1,2,3
a
#a,b,c
#a,1,b,cc,222,333

?F
#fine
foo(1)
foo(1,2)

#fail
#foo() 
#foo(a)
#foo(a,3)

*P
program foo;
begin
  let a:=3;
  foo(a);
end.
