S=if P S [$1?{$2}] |if P S else S [$1?{$2}{$3}] |while P S [$1{$2$2?}] |do S while P; [$1{$2P~?]}] |{S} [$1]|E; [$1] |; []
P=(E) [$1]
E=T |I=E [$2'$1!]
T=U<U [$1$2<] |U
U=S+T [$1$2+] |U-T [$1$2-] |T
T=I |N |P
I=$a
N=$+d
